services:
    pg:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        container_name: qadran-pg
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: postgres -c shared_preload_libraries=pg_textsearch
        ports:
            - "${FORWARD_DB_PORT}:${DB_PORT}"
volumes:
    postgres_data:
    redis:
